name: Tahfizul
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  modal_progress_hud: ^0.1.3
  flutter_staggered_animations: ^1.0.0
  smooth_star_rating: ^1.1.1
  toast: ^0.1.5
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  sqflite: ^2.0.0+3
  path: ^1.7.0
  path_provider: ^2.0.2
  shared_preferences: 
  image_picker: 
  image_cropper: ^1.2.3
  flutter_native_image: ^0.0.5
  dio: ^4.0.0
  flutter_rating_bar: ^3.1.0
  url_launcher: ^6.0.4
  ext_storage: ^1.0.3
  flutter_downloader: ^1.5.1
  permission_handler: ^8.1.3
  progress_dialog: ^1.2.0
  jitsi_meet: ^4.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  
  uses-material-design: true
  
  assets:
    - assets/images/
   

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 300

